- name: Misp
  hosts: localhost
  connection: local
  become: true

  vars:
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: present

  roles:
    - geerlingguy.docker

  tasks:
    - name: Clone MISP docker git
      ansible.builtin.git:
        repo: https://github.com/MISP/misp-docker.git
        dest: /opt/misp-docker
        version: master
      
    - name: Copy .env into misp-docker root
      ansible.builtin.copy:
        src: files/.env
        dest: /opt/misp-docker/.env
        mode: '0600'

    - name: Start MISP containers
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /opt/misp-docker
      
